name: Compare versions

inputs:
  new_version:
    description: "The new desired version"
    required: true
    type: string
  previous_version:
    description: "The previous version"
    required: true
    type: string

outputs:
  has_changed:
    description: "Has the version changed?"
    value: ${{ steps.check.outputs.changed }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: pip install semver==3.0.2
      shell: bash
    - run: |
        RESULT=$(pysemver compare ${{ inputs.new_version }} ${{ inputs.previous_version }})
        if [ "$?" -ne 0 ]; then
          echo "::error::Version is not a valid SemVer string"
          exit 1
        fi
        if [ "${RESULT}" -eq 0 ]; then
          echo "Version has not changed"
          echo "changed=false" >> $GITHUB_OUTPUT
        elif [ "${RESULT}" -eq 1 ]; then
          echo "Version has changed"
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "::error::Version change is invalid"
          exit 1
        fi
      shell: bash
