name: Parse data from aica-package.toml

inputs:
  directory:
    description: "Where the aica-package.toml is stored"
    required: false
    default: .
    type: string

outputs:
  name:
    description: "The name extracted from the aica-package.toml"
    value: ${{ steps.metadata.outputs.name }}
  version:
    description: "The version extracted from the aica-package.toml"
    value: ${{ steps.metadata.outputs.version }}
  ros_name:
    description: "The ROS name extracted from the aica-package.toml"
    value: ${{ steps.metadata.outputs.ros_name }}

runs:
  using: composite
  steps:
    - name: Install yq
      run: |
        if [ -x "$(command -v yq)" ]; then
          echo "yq already installed"
          exit 0
        fi

        VERSION=v4.40.5
        BINARY=yq_linux_amd64
        wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
          tar xz && mv ${BINARY} /usr/bin/yq
      shell: bash
    - name: Get metadata from aica-package.toml
      id: metadata
      run: |
        INPUT="${{ inputs.directory }}/aica-package.toml"
        NAME=$(yq '.metadata.name' $INPUT)
        ROS_NAME=$(yq '.metadata.ros-name' $INPUT)
        VERSION=$(yq '.metadata.version' $INPUT)
        echo "Name: $NAME"
        echo "Version: $VERSION"
        echo "ROS Name: $ROS_NAME"
        echo "name=$NAME" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "ros_name=$ROS_NAME" >> $GITHUB_OUTPUT
