name: Pick a Docker tag based from the GitHub workflow being run

outputs:
  tag:
    description: "The Docker tag"
    value: ${{ steps.pick.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Pick a tag
      id: pick
      run: |
        # develop-<run_number> if it's develop
        # latest if it's main
        # <tag> if it's a tag
        # <branch> if it's a branch (and replace / with -)
        GITHUB_REFER="${{ github.ref }}"
        BRANCH="${{ github.ref_name }}"
        RUN="${{ github.run_number }}"
        if [[ "${BRANCH}" == "develop" ]]; then
          TAG="develop,develop-${RUN}"
        elif [[ "${BRANCH}" == "main" ]]; then
          TAG="latest,main-${RUN}"
        elif [[ "${GITHUB_REFER}" == "refs/tags/"* ]]; then
          TAG="${GITHUB_REFER#refs/tags/}"
        else
          BRANCH_SAFE="${BRANCH//\//-}"
          TAG="${BRANCH_SAFE},${BRANCH_SAFE}-${RUN}"
        fi
        echo "Tag: ${TAG}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
      shell: bash
