name: Login to GHCR

secrets:
  token:
    description: "The GitHub token passed from the caller workflow"
    required: true

runs:
  using: composite
  steps:
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
